/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["**/*.{html, js}", "**/**/*.{html, js}", "./index.html"],
  theme: {
    screens: {
      md: '768px',
      lg: '1024px',
      xl: '1280px',
    },
    extend: {
      fontFamily: {
        'titillium': ['Titillium Web', 'sans-serif'],
      },
      backgroundColor: {
        'theme-purple': '#87509c',
        'theme-orange': '#eb7d4b',
        'theme-green': '#17c2a4',
        'deep-green': '#14a58c',
        'theme-gray': '#dfe8ed',
        'bright-sky': '#c8d9e5',
        'theme-sky': '#e7f1f8',
        'bright-yellow': '#e5c37f',
        'theme-yellow': '#ffdd99',
        'deep-yellow': '#e5c37f',
        'theme-pink': '#d74680',
        'deep-pink': '#b73c6d',
        'bright-blue': '#30bae7',
        'theme-blue': '#3c5499',
        'deep-blue': '#273a71',
      },
      borderColor: {
        'theme-orange': '#eb7d4b',
        'theme-sky': '#e7f1f8',
        'theme-green': '#14a58c',
        'bright-blue': '#30bae7',
      },
      padding: {
        '100': '2.4rem',
        '101': '3.7rem',
        '102': '4.5rem',
        '103': '5.3rem',
        '104': '5.7rem',
        '105': '6.6rem',
        '107': '7.8rem',
        '108': '8.3rem',
        '109': '10.8rem',
        '110': '14.5rem',
      },
      margin: {
        'service-item': '5.3%',
        'ico-item': '4.8%',
        'skill-item': '11.3%',
        'work-tab': '0.8%',
        'work-item': '1.7%',
        'blog-item': '6.3%',
        'input': '3.3%',
        'footer-item': '6.3%',
        '100': '1.4rem',
        '101': '14.7rem',
      },
      fontSize: {
        'normal': ['1.6rem', { lineHeight: '1.2' }],
        'normal-md': ['2.4rem', { lineHeight: '1.2' }],
        'xl-txt': ['4rem', { lineHeight: '1.2' }],
        '2xl-txt': ['4.2rem', { lineHeight: '1.2' }],
        'medium': ['2.1rem', { lineHeight: '1.5' }],
      },
      width: {
        'nav-list': '53%',
        'meet-list': '83%',
        'service-list': '82%',
        'skill-list': '78%',
        'service-item': '21%',
        'item-medium': '47.3%',
        'skill-item': '16.1%',
        'work-tab': '8.6rem',
        'work-list': '86%',
        'work-item': '49%',
        'blog-item': '46.8%',
        'form-blk': '67%',
        'input': '48%',
        'footer-list': '74%',
      },
      height: {
        'blog-img': '9.6rem',
        'nav-btn': '3.5rem',
      },
      textColor: {
        'deep-blue': '#3c4761',
        'bright-blue': '#30bae7',
        'bright-yellow': '#ffdd99',
        'bright-blue': '#30bae7',
      },
      lineHeight: {
        11: '2.4rem',
      },
      spacing: {
        99: '100vw',
      }
    },
  },
  plugins: [],
}

